### ISSUE TITLE
Doesn't Work for PASS replacements

### ISSUE THREAD

**Issue by candywal** [timstoddard/PassThePlebs#15]
Doesn't work on Degree Planner or Schedule Builder. Is there a way to add a function for it to just run on the portal?

**Comment by timstoddard** [comment]
This extension was developed for the old version of PASS that is no longer in use. If you want to build a new version that integrates with the current Degree Planner/Schedule Builder, feel free to use this repo as a guide. I’m no longer a student at Cal Poly so I’m not working on this anymore.
