### ISSUE TITLE
Link to wrong instructor

### ISSUE THREAD

**Issue by skhillon** [timstoddard/PassThePlebs#2]
1. In PolyPlanner add `CSC 348 - Discrete Structures`
2. Instructor is `Christopher Siu`, click on his Polyratings link
3. Goes to `Lesiuk, Veronika` which contains the string `siu`, but is not the correct person

**Comment by timstoddard** [comment]
Yeah thats an issue with Polyratings, I use their search function to find teachers by the name listed on PASS. If you go to https://polyratings.com and search for the term "siu", it will take you to Lesiuk's page.

One thing I could do is start a list of teachers that don't have Polyrating pages, and manually update that list when I find other teachers (I've encountered this problem several times before), but then we run the risk of not linking to one of those teachers once they have a Polyratings page created for them; better to be safe then sorry I guess. If I had a good amount of time to pour into this (I really don't, currently) I would probably reach out to the guys that run Polyratings and see if they would let me refactor their search function, or just create profiles for teachers that don't have profiles yet. [Sidenote: their db could use a lot of cleanup, first and foremost I would highly recommend making the teacher names in the db match exactly what is on PASS, but that's an issue for another day]

For now, I'll just start that list I mentioned above; it's not a comprehensive solution but it'll fix the problem for the time being.
